Added option to use custom distinct id
cryptosense/flask-mixpanel pull request #1
Opened 2019-04-03 08:09 UTC by eXenon

This is useful when the session has no distinct ID defined.

2019-04-03 08:17 UTC, bbc2 requested changes
Have you had a chance to test it with your work?  If yes then I'll merge this and release a new version.

2019-04-03 08:17 UTC, bbc2 commented on CHANGELOG.rst
> +`Unreleased`_ (2019-04-03)
No date until released.

2019-04-05 07:05 UTC, eXenon commented
Change tested locally with testing project in mixpanel. It worked just as expected!

2019-04-05 07:55 UTC, bbc2 approved these changes

2019-04-05 07:56 UTC, merged